### ISSUE TITLE
jwst_pancake __init__.py

### ISSUE THREAD

**Issue by muuud** [spacetelescope/pandeia-coronagraphy#20]
If the VERSION file is missing, from installing by hand the following lines in `__init__.py` prevent importing jwst_pancake
```
try:
    version_file = os.path.join(os.path.split(__file__)[0], "VERSION")
    with open(version_file, "r") as inf:
        __version__ = inf.readline().strip()
except Exception as e:
    sys.err.write("Unable to find pancake version file!\n")
```

sys.err should be replaced by [sys.stderr](https://docs.python.org/3/library/sys.html#sys.stderr)

**Comment by mperrin** [comment]
Fixed now. This issue was in fact noticed and a fix provided in PR #17, submitted by @eslavich back in November, but no one merged that PR until now.
