### ISSUE TITLE
Cleanup already-merged branches

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/pandeia-coronagraphy#4]
Right now in addition to `master`, this repo has several branches: `cache`, `contrasts`, `nircam_offsets`, and `pandeia1.1`. I just checked and all of these appear to have already been merged into `master` at various points in the past; as far as I can tell there are no new commits on any of them. 

Since they're already merged,  I think they can & should be deleted at this point. Any objections?

**Comment by kjbrooks** [comment]
No objections from me!

**Comment by mperrin** [comment]
done!
